Hardening tests, so that they run on travis
It seems like we have a newline problem:

    filterStringThroughProcess(org.buildobjects.process.ProcBuilderTest)  Time elapsed: 0.05 sec  <<< FAILURE!

    org.junit.ComparisonFailure: expected:<x a z[

    ]> but was:<x a z[]>

Also, uuidgen is not installed on the travis machine:

    testCanCallRunMultipleTimes(org.buildobjects.process.ProcBuilderTest)  Time elapsed: 0.012 sec  <<< ERROR!

    org.buildobjects.process.StartupException: Could not startup process 'uuidgen '.